### ISSUE TITLE
Issues with Deploy and Access workload instructions in AWS 

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#332]
- [Access Workloads Using an Internal Load Balancer](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/deploy-workloads.html#with-lb) these instructions will create an external load balancer. For internal load balancer an annotation needs to be provided.
- [Access Workloads Using an External Load Balancer](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/deploy-workloads.html#external-lb) - the service type under these instructions is NodePort which is wrong. The instructions [Access Workloads Using an Internal Load Balancer](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/deploy-workloads.html#with-lb) can be used for this topic.

**Comment by outofmem0ry** [comment]
For Internal load balancer `annotations` tag is required under service's metadata section. Example modification below

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: LoadBalancer
```
